CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  is_collection INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT '',
  updated_at INTEGER NOT NULL DEFAULT 0,
  package_id TEXT NOT NULL DEFAULT '',
  deps TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS crawl_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  cursor TEXT NOT NULL DEFAULT '*',
  todo_ids TEXT NOT NULL DEFAULT '',
  total_processed INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0
);
