name: Bug Report
description: Create a bug report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Create a bug report to help us improve
  - type: input
    id: version
    attributes:
      label: Version
      description: What version / commit are you using?
      placeholder: Version number or commit hash
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: Windows 11, macOS (ARM64), Arch Linux, etc.
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: Clearly describe the bug and steps to reproduce.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please provide any relevant log output.
      placeholder: Paste log output here
  - type: textarea
    id: extra_info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
