from __future__ import annotations

from PySide6.QtCore import QEasingCurve

# Animation
ACCORDION_ANIMATION_DURATION_MS = 200
ACCORDION_EASING = QEasingCurve.Type.OutCubic

# Banner
BANNER_MAX_HEIGHT = 260
BANNER_OVERLAY_HEIGHT = 120

# Responsive
META_GRID_BREAKPOINT = 500

# Layout
RAIL_MIN_WIDTH = 52
RAIL_MAX_WIDTH = 180
RAIL_COLLAPSE_WIDTH = 116
SIDEBAR_WIDTH = 240

# Interaction
TOOLTIP_DELAY_MS = 400
